name: Build and Release for Windows

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Dependencies
      - name: Install Dependencies 
        run: |
          choco install llvm cmake ninja --installargs 'ADD_CMAKE_TO_PATH=System' --yes
          setx PATH "%PATH%;C:\Program Files\LLVM\bin"
          clang-cl --version
          cmake --version
          ninja --version

      # Configure Build
      - name: Configure Build
        run: cmake --preset=windows-release

      # Build Project
      - name: Build Project
        run: |
          cmake --build build/release/windows

      # Create GitHub Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      # Upload Windows Binary
      - name: Upload Windows Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/app
          asset_name: app-windows
          asset_content_type: application/octet-stream
