name: Build and Release for Linux

on:
  release:
    types:
      - created 

jobs:
  build-and-release:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo apt-get install -y clang-18 lld-18 libc++-18-dev libc++abi-18-dev libfuse2 cmake ninja-build zip wget
          clang-18 --version
          cmake --version
          ninja --version

      - name: Configure Build
        run: cmake --preset=linux-release

      - name: Build Project
        run: |
          cmake --build build/release/linux

      - name: Create an AppImage
        run: |
          BINARY_PATH="./bin/app"
          APP_DIR="./AppDir"
          APPIMAGE_TOOL="appimagetool-x86_64.AppImage"

          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/$APPIMAGE_TOOL
          chmod +x $APPIMAGE_TOOL

          mkdir -p $APP_DIR/usr/bin $APP_DIR/usr/lib
          cp $BINARY_PATH $APP_DIR/usr/bin/

          cp ./assets/icon.png $APP_DIR

          ldd $BINARY_PATH
          for lib in $(ldd $BINARY_PATH | awk '{ if ($3 ~ /^\//) print $3 }'); do
            echo "adding $lib to shared libs"
            cp --parents "$lib" "$APP_DIR/usr/lib/"
          done

          cat > $APP_DIR/app.desktop <<EOL
          [Desktop Entry]
          Type=Application
          Name=APP-TEST
          Exec=app
          Icon=icon
          Categories=Game;
          EOL

          cat > $APP_DIR/AppRun <<EOL
          #!/bin/bash
          HERE="\$(dirname "\$(readlink -f "\$0")")"
          export LD_LIBRARY_PATH="\$HERE/usr/lib:\$LD_LIBRARY_PATH"
          exec "\$HERE/usr/bin/$(basename $BINARY_PATH)" "\$@"
          EOL
          chmod +x $APP_DIR/AppRun

          ./$APPIMAGE_TOOL $APP_DIR "app.AppImage"

      - name: Zip results
        run: |
          zip -r output.zip assets app.AppImage

      # Upload Linux Binary
      - name: Upload Linux Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./output.zip
          asset_name: app-linux.zip
          asset_content_type: application/octet-stream
